### ISSUE TITLE
Can't push :(

### ISSUE THREAD

**Issue by DanStix** [GalOz666/qa_training_repo#1]
Permission to GalOz666/qa_training_repo.git denied to DanStix. unable to access 'https://github.com/GalOz666/qa_training_repo.git/': The requested URL returned error: 403

**Comment by GalOz666** [comment]
this is a good thing that you can't push....we only have master branch. create your own branch!

**Comment by GalOz666** [comment]
https://guides.github.com/activities/hello-world/#:~:text=Pull%20Requests%20are%20the%20heart,the%20content%20from%20both%20branches.
